### ISSUE TITLE
"stack test" never runs tests

### ISSUE THREAD

**Issue by BLandorff** [atom-haskell/ide-haskell-cabal#21] opened 2018-02-09 12:19 UTC
Instead, it says "Test running disabled by --no-run-tests flag."
(So it builds the tests, but doesn't run them. A quick look at the code suggests runBuild() in stack.ts might be the culprit).
Same for bench, except there's no message blaming the flag.

**Comment by lierdakil** [comment] 2018-02-09 12:39
Thank you for the report. From what I could tell after a couple tests, the issue was caused by an overzealous component selection. As a consequence, you've had to have test component either explicitly selected as the target, or have a test-related source file open -- otherwise, tests wouldn't even build in most cases let alone run.

Should be fixed in 2.1.2. Let me know how it goes. 

Thanks again.

**Closed as completed** 2018-03-03 15:51 UTC
Labels: bug
